### ISSUE TITLE
Introduce build tool

### ISSUE THREAD

**Issue by franc90** [xmslyz/LuhnAlgorithm#1]
Build tools allow for simpler application development and easier code sharing.
There are 2 prevailing apps for java: [gradle](https://docs.gradle.org/current/userguide/userguide.html) and [Apache maven](https://maven.apache.org/run.html)

in order to introduce gradle:
1. install gradle on your computer
2. in root directory of the project create files: `settings.gradle` (empty) and `build.gradle` with this content:
```
plugins {
    id 'java-library'
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
}

jar {
    manifest {
        attributes 'Main-Class': 'LuhnAlgorithm'
    }
}
```
3. [optional] run `gradle wrapper`
4. to build project run `./gradlew build` (or  `gradle build` if skipped `3`)
5. to run application run `java -jar build/libs/LuhnAlgorithm.jar`

in order to install Apache maven
1. install maven on your computer
2. in root directory of the project create file `pom.xml` with this content:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.xmslyz.luhn</groupId>
    <artifactId>LuhnAlgorithm</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>
    <build>
        <sourceDirectory>src/</sourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>libs/</classpathPrefix>
                            <mainClass>
                                LuhnAlgorithm
                            </mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```
3. [optional] run ` mvn wrapper:wrapper`
4. to build project run `./mvnw package` (or `mvn package` if skipped `3`) 
5. to run application run `java -jar target/LuhnAlgorithm-1.0-SNAPSHOT.jar`

Side note: the code of this application is located in `src` directory while industry-standard is to put it inside `src/main/java`. Putting it according to standard will simplify `pom.xml`: directive `sourceDirectory` will no longer be necessary; and `build.gradle`: you can remove `sourceSets` then.

**Comment by xmslyz** [comment]
Hi. Im new in Java. What is the purpose of those additions?

**Comment by franc90** [comment]
There are multiple reasons to use a build tool instead of relying on an [IDE](https://en.wikipedia.org/wiki/Integrated_development_environment) (IntelliJ IDEA in your case), but for a beginner I think those 2 are the most important:
1. Currently, you can run your code from the IDE, but not from anywhere else (at least not easily). To distribute your app/library (to allow others to run it or make it easier for yourself to do it outside of IDE), you should package it. In Java world those packages are called [JAR files](https://en.wikipedia.org/wiki/JAR_(file_format)). JAR file is basically a zip file with compiled code and some additional files that tell the [JVM](https://en.wikipedia.org/wiki/Java_virtual_machine) how to run application. 
You can create JARs manually but it's a tedious process that can be greatly simplified by using build tools. 

2. Build tools manage dependencies of your project. Currently there are no external dependencies in your code, but I presume you will soon need to introduce at least some testing framework - so that you can easily automate tests (performing tests manually is highly error-prone, automate when possible!)

Above, in the issue description I proposed 2 build tools (gradle and maven) and described how to introduce them in the project. You should choose only one of them.

**Comment by xmslyz** [comment]
Thank You. I will read about the subject. Thanks for letting me know.

**Comment by xmslyz** [comment]
Poczytałem i poszukałem. Zacznę od Mavena. Zapowiada się ciekawie. Dziękuję za pomoc i sugestie. Programik już bryka z jar'a w terminalu.

**Comment by franc90** [comment]
Świetnie, Padre! :) 
Dorzuciłem [pull request](https://github.com/xmslyz/LuhnAlgorithm/pull/2), który sprząta niepotrzebne pliki w repozytorium. Jeśli uważasz, że zmiany w nim są  w porządku, możesz go [zmergować](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request).

Jeśli tylko pasuje Ci taka forma edukacji (githubowymi issue'sami) i masz chęć kontynuować, to chętnie dodam kolejny issue z propozycją co można zrobić, żeby pchnąć projekt odrobinę dalej.

**Comment by xmslyz** [comment]
Super. Przyjrzę się temu wieczorem i przyjrzę się tym zmianom aby zrozumieć ich logikę. 

Nie ukrywam, że to moje hobby, więc każda forma uczenia się czegoś nowego jest jak najbardziej poszukiwana. Głównie uczę się z podręczników, YouTube'a i rozwiązywania zadań które gdzieś wynajduje w sieci lub sam sobie je stawiam jako wyzwania. 

wcześniej uczyłem się w ten sam sposób Pythona, teraz dla urozmaicenia dorzuciłem Javę.

**Comment by franc90** [comment]
Ja się tym param zawodowo, choć od paru lat znacznie mniej w javie. Ale z doświadczenia wiem, że ktoś kto podpowie gdzie szukać dalej jest na początku bardzo pomocny.

Zmiany, które zaproponuję jak najbardziej będą zgodne z tym jak się pisze w javie, ale pokażą też ogólne mechanizmy, które będziesz mógł użyć w (prawie?) każdym innym języku programowania.
