### ISSUE TITLE
General remarks and few suggestions

### ISSUE THREAD

**Issue by jpogorzelski** [xmslyz/LuhnAlgorithm#10]
Na wstępie - dobra robota :) Ja przez przez pierwsze 2 lata w Javie umiałem zrobić niewiele ponad Hello World :)
Uwagi w kolejności występowania (klasy/pakiety IDE sortuje alfabetycznie):

1.  interfejs `Computation`  
 - intencje wg mnie bardziej oddałaby nazwa `Computable` - zwłaszcza w przypadku interfejsów funkcyjnych (posiadających jedną metodę), patrz np `Runnable`, `Comparable` w JDK (biblioteka standardowa Java).
 - wydaje się, że parametr metody `compute` może być ciągiem znaków (String), więcej info poniżej
3.  `LuhnChecksumComputing`
  - jako serce logiki biznesowej nie powinna zajmować się parsowaniem Stringów (nie mylić z prasowaniem stringów, niedorzeczna czynność... :wink:  ), toteż parametr wejściowy dałbym typu liczbowego - proponuję użyć wzorca ValueObject i opakować to w klasę, która wykona walidację podczas jej tworzenia, wtedy mamy pewność że obiekt przekazany do `compute` jest już poprawnie utworzony, coś w stylu:
  ```java
public class LuhnCandidate {
    private final BigInteger number;

    private final String[] digits;

    public LuhnCandidate(String input) {
        if (input == null || input.isEmpty()) {
            throw new IllegalArgumentException("Expected non-empty string");
        }
        try {
            var trimmedInput = input.trim().replace(" ", "");
            this.number = new BigInteger(trimmedInput);
            this.digits = trimmedInput.split(""); //or .toCharArray()
            if (this.number.signum() < 0) {
                throw new IllegalArgumentException("Expected number >= 0");
            }
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Expected a number");
        }

    }

    public BigInteger getNumber() {
        return number;
    }

    public Integer getDigitCount() {
        return digits.length;
    }

    public String[] getDigits() {
        return digits;
    }
}
```
 
- w sumie wszystkie pola w klasie mogę być zmiennymi lokalnymi przekazywanymi do kolejnych metod jako argumenty, np;
 ```java
...
var array = setArray(number.length());
var wagedArray = multiplyWages(array);
int total = countTotal(wagedArray);
String checksum = getChecksum(number, total);
...
```

Reszta jutro, idę usypiać Franka :)

**Comment by xmslyz** [comment]
tej części nie rozumiem.

```java
...
var array = setArray(number.length());
var wagedArray = multiplyWages(array);
int total = countTotal(wagedArray);
String checksum = getChecksum(number, total);
...
```

np. metoda multiplyWages przechodzi przez obiekty array i mnoży co drugi. Co miała by zwracać?
A z drugiej strony jeśli ją złoszę jako lokalną, to jak będę mógł z niej skorzystać w pozostałych metodach? 
Czy może źle odczytałem lub zniezrozumiełem twojej sugestii?

**Comment by xmslyz** [comment]
i jak robisz, że u ciebie jest kolorowy tekst kodu??? :]

**Comment by jpogorzelski** [comment]
> i jak robisz, że u ciebie jest kolorowy tekst kodu??? :]

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks 
```
```java
kodzik
`` `
```

**Comment by xmslyz** [comment]
już umię 👍🏼

**Comment by jpogorzelski** [comment]
> tej części nie rozumiem.
> 
> ```
> ...
> var array = setArray(number.length());
> var wagedArray = multiplyWages(array);
> int total = countTotal(wagedArray);
> String checksum = getChecksum(number, total);
> ...
> ```
> 
> np. metoda multiplyWages przechodzi przez obiekty array i mnoży co drugi. Co miała by zwracać? A z drugiej strony jeśli ją złoszę jako lokalną, to jak będę mógł z niej skorzystać w pozostałych metodach? Czy może źle odczytałem lub zniezrozumiełem twojej sugestii?

Faktycznie ta część algorytmu mutuje oryginalną tablicę, więc mogłaby np. ją skopiować na początku i zwrócić zmodyfikowaną kopię. Do poczytania np
https://www.baeldung.com/java-array-copy
