### ISSUE TITLE
2. Separate logic from application code

### ISSUE THREAD

**Issue by franc90** [xmslyz/LuhnAlgorithm#3]
Algorytm Luhna jest stosunkowo prosty: na wejściu przyjmuje liczbę, wykonuje na niej kilka prostych operacji, a rezultatem jego wykonania jest inna liczba. Sugeruje to, że powinien istnieć [interfejs](https://www.baeldung.com/java-interfaces) `LuhnAlgorithm`, który będzie definiował sposób użycia algorytmu:

```java
public interface LuhnAlgorithm {
    String compute(String input)
}
```
Implementacje tego interfejsu będą zmuszone być zgodnymi z nim, co je ujednolici i ułatwi testowanie.

Obecnie, w repozytorium istnieją dwie implementacje algorytmu Luhna, ale obie cierpią na pomiszanie logiki obliczającej algorytm z kodem obsługującym interakcję z użytkownikiem. Taka sytuacja utrudnia rozwijanie projektu, ulepszanie algorytmu oraz testowanie kodu.

Aby to poprawić, użyjmy javowych pakietów na odseparowanie różnych części kodu:
- `com.xmslyz.luhn.logic` - tutaj powinien znaleźć się interfejs `LuhnAlgorithm` oraz jego implementacje:
```java
public class MyGreatImplementationOfLuhnAlgorithm extends LuhnAlgorithm {
    public String compute(String input) {
        // kodzik
    }
    // więcej kodziku
}
```
- `com.xmslyz.luhn.app` - tutaj umieść kod dotyczący interakcji z użytkownikiem. Klasę nazwij `App` albo `Main`, żeby sugerowała, że jest to część projektu odpowiadająca za interakcję ze światem zewnętrznym. Powinny się tu znaleźć wszystkie wywołania `System.out.println` lub `Scanner`. Kodzik tutaj będzie też odpowiadał za wywołanie odpowiedniej implementacji `LuhnAlgorithm`. Powinno to wyglądać jakoś tak (tylko poglądowo, finalnie kodziku będzie pewnie więcej):
```java
public class App {
  public static void main( String[] args ) {
    LuhnAlgorithm luhnAlgorithm = new MyGreatImplementationOfLuhnAlgorithm()
    var scanner = new Scanner(System.in); // w javie nie zawsze trzeba pisać typy zmiennych
    System.out.println("Podaj numer, do którego ma być dodana cyfra kontrolna:");
    var input = scanner.nextLine();
    var output = luhnAlgorithm.compute(input);
    System.out.println(output);
  }
}
```

---
### Jak wprowadzać zmiany
git umożliwia bardzo elastyczne tworzenie i mergowanie branchy ([przyjemny tutorial](https://learngitbranching.js.org/?locale=pl) pozwoli to dobrze zrozumieć i sobie zwizualizować). Rozpoczynając nową serię zmian warto robić to na branchu, a w momencie, kiedy stan prac na nim będzie zadowalający, zmergować go do głównego brancha repoztorium: `master`. (see [github flow](https://docs.github.com/en/get-started/quickstart/github-flow))
Pozwala to na jednoczesny rozwój projektu w wielu kierunkach i uniezależnia główny branch od niepełnych zmian (tylko skończona praca jest wmergowana).

Zanim zaczniesz wyżej opisaną pracę:
1. Stwórz branch (e.g. `logic-separation)`: `git checkout -b logic-separation`
2. Wprowadzaj zmiany na branchu normalnie commitując do niego
3. Wypychaj do repozytorium: `git push origin logic-separation`
4. Gdy będzie gotowe, otwórz [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

**Comment by xmslyz** [comment]
Nie do końca rozumiem tę część, że cała interakcja z użytkownikiem ma się odbywać w main /app. Czy to znaczy, że zbędna jest clasa OptionMenu, i że słuszniejszym rozwiązaniem jest aby większość bloku kodu umieścić w main?

```
public class App {
  public static void main( String[] args ) {
    LuhnAlgorithm luhnAlgorithm = new MyGreatImplementationOfLuhnAlgorithm()
    var scanner = new Scanner(System.in); 
/* tutaj menu opcji kod / wyjście ??? 
a następnie */
    System.out.println("Podaj numer, do którego ma być dodana cyfra kontrolna:");
    var input = scanner.nextLine();
    var output = luhnAlgorithm.compute(input);
    System.out.println(output);
  }
}

```

**Comment by franc90** [comment]
[Wujek Bob](https://en.wikipedia.org/wiki/Robert_C._Martin) zaproponował [5 zasad](https://pl.wikipedia.org/wiki/SOLID_(programowanie_obiektowe)), które pomagają w stworzeniu dobrego oprogramowania. Pierwszą z nich jest [The Single Responsibility Principle](https://blog.cleancoder.com/uncle-bob/2014/05/08/SingleReponsibilityPrinciple.html), którą można streścić do:
> Gather together the things that change for the same reasons. Separate those things that change for different reasons.

---

> Czy to znaczy, że zbędna jest clasa OptionMenu, i że słuszniejszym rozwiązaniem jest aby większość bloku kodu umieścić w main?

Jej istnienie niekoniecznie jest błędem. Gdy patrzę na to co robią klasy `Luhn` oraz `OptionMenu` to widzę, że
1. `OptionMenu` zajmuje się komunikacją z użytkownikiem oraz uruchomieniem algorytmu Luhna
2. `Luhn` jedynie uruchamia `OptionMenu`, nie ma żadnej innej odpowiedzialności  

To sugerowałoby, że mogą być one niepotrzebnie rozdzielone. Ale jeśli planujesz rozbudować `Luhn` np. o wczytywanie konfiguracji, pobieranie danych z dodatkowego źródła zewnętrznego, to można zostawić jak jest.  
To czy kod z `OptionMenu` będzie wywoływany bezpośrednio z `main` czy tak jak jest teraz, jest detalem.

Deklaracja `OptionMenu` wygląda tak:
```
public class OptionMenu extends Motor
```
i tu jest dużo większy problem. Pomiędzy obiektami mogą zachodzić 3 rodzaje relacje:
- dziedziczenie, które użyłeś, opisuje że jakiś obiekt jest też innego, szerszego typu, np. ford jest samochodem
- kompozycja, mówi o tym, że jakiś obiekt zawiera inne obiekty - i te inne obiekty nie mają sensu bez niego, np. ford ma karoserię (karoseria forda nie ma sensu bez forda)
- agregacja, jest podobna do kompozycji: obiekt zawieraja inne obiekty, ale te obiekty nie są nim ograniczone np. ford ma kierowcę (ale kierowca może się przesiąść na rower, nie potrzebuje forda do istnienia)

Mając tę perspektywę, widać, ze `OptionMenu` nie powinien dziedziczyć po `Motor`. Powinna zachodzić relacja kompozycji lub nawet agregacji.

```
public class OptionMenu {
  private Motor motor = // itd
}
```
----
(jako taka notatka z boku warto pamiętać, że inżynieria oprogramowania ma w sobie odrobinę ze sztuki i te zasady :arrow_up: są bardziej wskazówkami, które czasem warto łamać - choć wiedza o tym kiedy to zrobić, przychodzi z doświadczeniem)

**Comment by xmslyz** [comment]
Naprawdę bardzo sobię cenię ten "tutorial live". Czym innym jest poznawanie teorii i uczenia się funkcjonowania programu, a czym innym zdrzenie z rzeczywistością implementacji zdobytej wiedzy w praktyce programowania.

**Comment by franc90** [comment]
Programowanie to bardzo praktyczna działka, a z historii wiemy, że takich najlepiej uczy się terminując u rzemieślnika. 
Samemu znajduję w tej współpracy przyjemność. Ale też dobrze sobie powtarzać co jakiś czas podstawy - a nie znam lepszej metody niż tłumacząc komuś "świeżemu".
Na początku mnóstwo błędów związanych jest z brakiem doświdczenia i niewiedzą gdzie pójść dalej. Łatwo można się zakopać w dołku, z którego ciężko będzie się wydostać i w konsekwencji zniechęcić się. Stąd przydaje się ktoś kto wskaże kierunek.  
I w sumie w twojej "branży", Padre, jest chyba podobnie. :wink:

**Comment by xmslyz** [comment]
Nie ukrywam, że za każdym razem kiedy myślę: "o super, zrobię tak i tak" i potem dostaję w PR. "Nie tak. Nie tędy droga" to jest tem moment "czy ja się tego w ogóle nauczę, czy mi to potrzebne". Ale jednak trener nie jest po to aby oszczędzać zawodnika. Dlatego dziękuję za twoje chęci. Że ci się chce uczyć "młodego".
