### ISSUE TITLE
3. Add tests for luhn algorithm

### ISSUE THREAD

**Issue by franc90** [xmslyz/LuhnAlgorithm#5]
Po wyodrębnieniu obliczania algorytmu luhna do osobnego pakietu i dodaniu interfejsu, powinieneś dodać testy jednostkowe testujące poprawność implementacji algorytmu.

Pakiet jest logicznie zamkniętą (spójną) jednostką kodu. Utworzenie interfejsu (jednego lub więcej) do klas w nim zawartych pozwala nawiązać kontrakt z klasami w innych pakietach. Dzięki temu kontraktowi możesz dowolnie zmieniać implementację (np. poprawiać błędy, przyspieszać algorytm), o ile będzie zgodna z interfejsem. Dbasz w ten sposób o higienę kodu. Pamiętaj: interfejs powinien zawierać minimalną liczbę jak najprostszych metod potrzebnych do poprawnego uruchomienia klas go impementujących!

Instrukcja co należy zrobić w ramach zadania:
1. W `pom.xml` usuń `<sourceDirectory>src/</sourceDirectory>`
2. Zmień strukturę kodu na zgodną ze standardem mavenowym:
W katalogu `src/` utwórz podkatalog `src/main/java` i przenieś tam cała kod, który do tej pory znajdował się w `src/`
3. Utwórz katalog `src/test/java` - tutaj będziesz dodawał testy do kodu.  
Podział na `main` oraz `test` pozwala na wyodrębnienie kodu testowego, który nie jest potrzebny do działania aplikacji. Więcej przeczytasz [tutaj](https://www.baeldung.com/java-unit-testing-best-practices).
4. W `pom.xml` dodaj zależność na junit:
```
	<dependencies>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>5.9.1</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
```
a w sekcji `plugins` 2 nowe pluginy, które umożliwią uruchamianie testów przez mavena:
```
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M6</version>
            </plugin>
```
5. W `src/test/java` dodaj klasę testową `com.xmslyz.luhn.logic.LuhnChecksumComputingTest`:
```
package com.xmslyz.luhn.logic;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class LuhnChecksumComputingTest {

    private Computation computation = new LuhnChecksumComputing();

    @Test
    void wikipedia_example() {
        var result = computation.compute("7992739871");

        assertEquals("79927398713", result);
    }
}
```
a następnie dopisz kilka kolejnych przypadków testujących jak algorytm powinien się zachować gdy otrzyma na wejściu:
- coś co nie jest liczbą
- liczbę ujemną
- pusty string
- "0"
- "1"
- kilka znanych przypadków (taki jak ten :arrow_up: z wikipedii)
- inne "dziwne" przypadki, które wymyślisz

Po dodaniu każdego z tych przypadków, uruchom test i upewnij się że przechodzi - jeśli nie, to popraw kod.

---
Po zakończeniu zadania struktura kodu w repozytorium powinna wyglądać tak:
![image](https://user-images.githubusercontent.com/5007894/195633982-34cad557-76b2-4b8f-bc08-921f49415527.png)
a po uruchomieniu budowania projektu: `mvn package` powinna pojawić się sekcja z testami:
![image](https://user-images.githubusercontent.com/5007894/195634292-2c7a78c6-61c2-4064-92de-9b12012b5ccb.png)

**Comment by xmslyz** [comment]
Testowanie jest równie ciekawe co pisanie. Nie wiedziałem, że to takie wciągające szukanie wyjąktów i szukanie sposobów na radzenie sobie z nimi. Dziękuję !!! Nie wiem tylko czy dobrze zrobiłem, że scomitowałem po testach do mastera. 

Jedynie to nie ograniam tej części z Assert.... przysiąde i w wolnym czasie sobie pocztam o opcjach. Na ile zrozumiałem, to mam tam wpisać wynik jaki ja oczekuję?

**Comment by franc90** [comment]
Trochę szkoda, że nie zrobiłeś tego na osobnym branchu i nie otworzyłeś PR, bo miałbym kilka uwag do testów.

Wszystkie testy, które nie mają asercji "przechodzą" - tzn. obliczenie się wykonuje, nie jest rzucany żaden wyjątek, ale nie sprawdzasz wyniku. Np. test:
```
    @Test
    void visaNumber(){
        var result = computation.compute("400360000000001");
    }
```
jedynie sprawdza, że coś się wykonuje, ale ponieważ nie testuje rezultatu, to gdybym podmienił implementację metody `compute` na:
```
public String compute(String input) {
    return "";
}
```
test cały czas by przechodził! Nie wiedziałbyś że coś jest nie tak. Po to potrzebujesz asercji, żeby upewnić się, że kod nie tylko jest uruchamiany i się nie wywraca, ale i działa w sposób oczekiwany. 
```
    @Test
    void visaNumber(){
        var result = computation.compute("400360000000001");

        assertEquals("4003600000000014", result);
    }
```
dodanie tej asercji sprawia, że jeśli rezultat wywołania `compute` jest inny od oczekiwanego test nie przechodzi.

**Comment by franc90** [comment]
w sytuacjach wyjątkowych - np. gdy ktoś poda `null`, albo parametr, który nie jest liczbą, zdecydowałeś się na złapanie wyjątku, wypisanie `Input error.` i zwrócenie `null`. To jest błąd w architekturze. Część `logic` nie powinna komunikować się bezpośrednio z użytkownikiem. Jeśli dostanie niepoprawny argument, powinna  wyrzucić odpowiedni wyjątek, a jej klient dopowiendnio go obsłużyć (u Ciebie część w `main`: np. wypisując `Input error.`).  
Powinieneś dodać walidację wartości `input`, np.:
```java
public String compute(String input) {
    if (string == null) throw new NullPointerException("expected not-null input");
    Integer.parseInt(input.trim().replace(" ", ""));
    /// reszta kodziku
}
```
 a następnie sprawdzać w teście, że odpowiedni wyjątek został rzucony:
```java
    @Test
    void nullInput() {
        Assertions.assertThrows(                     // upewnij się że będzie rzucony wyjątek
                NullPointerException.class,          // typu NullPointerException
                () -> computation.compute(null),     // gdy uruchomię compute z parametrem null
                "expected not-null input"            // dodatkowo wyjątek powinien mieć taką wiadomosć
        );
    }
```

**Comment by franc90** [comment]
P.S. test jest w pakiecie `com.xmslyz.luhn.logic`, więc powinien być w folderach: `src/test/java/com/xmslyz/luhn/logic`
