### ISSUE TITLE
4. Run tests on every push

### ISSUE THREAD

**Issue by franc90** [xmslyz/LuhnAlgorithm#7]
Dodałeś testy jednostkowe do projektu. Zautomatyzujmy ich uruchamianie jeszcze bardziej. 
Żeby mieć więcej pewności że zmiany pushowane do repozytorium są poprawne ustaw githubową akcję, która automatycznie uruchomi te testy i otaguje PullRequest wynikiem testu.

Instrukcja jak to zrobić jest w tym wpisie na blogu: [link](https://blog.codeleak.pl/2020/06/gh-actions-maven-junit5.html). Ma on jednak 2 lata i nie wszystko musi się idealnie zgadzać z obecnym githubem.

- zmiany wrzuć na osobnym branchu, przez pull request - od razu będziesz widział czy "zadziałało"
- pamiętaj, że uruchamiamy kod na javie 17, w artykule jest setup dla 14 (prawdopodobnie wystarczy zmienić numerek, nie sprawdzałem)

**Comment by xmslyz** [comment]
W chwili obecnej mam 4 branch'e

master
logic
testsBranch
testsPush

logic już został zmergowany. 

a co zrobić z kolejnymi gałęziami? megrować je wedle jakiego klucza? który pierwszy? bo na przykład ten test computa z Longiem czy zmiany z BigInteger są w jednym a w drugim już nie.
