### ISSUE TITLE
5. Fix validation

### ISSUE THREAD

**Issue by franc90** [xmslyz/LuhnAlgorithm#9]
W kodzie jest obecnie wiele błędów i miejsc na poprawki. 

## W klasie `LuhnChecksumComputingTest`
```
    @Test
    void negativeNumber(){
        assertThrows(InputValidationException.class,
                () -> computation.compute(String.valueOf(Integer.parseInt("-4"))),
                "negative number");
    }
```
to jest przekombinowane. `"-4"` to już jest string. Najpierw zamieniasz `"-4"` na `int` `-4`, a następnie na powrót w stringa `"-4"`. `String.valueOf(Integer.parseInt("-4"))` to to samo co `"-4"`.

---

```
    @Test
    void notANumber() {
        assertThrows(NumberFormatException.class, () -> computation.compute(String.valueOf(Integer.parseInt("1q234"))),
                "Not a number");
    }
```
zawsze przechodzi (niezależnie od implementacji metody `compute`). Wyjątek `NumberFormatException` jest rzucany nie przez `computation.compute`, a przez `Integer.parseInt`!  
`computation.compute(String.valueOf(Integer.parseInt("1q234")))` to jest przekombinowane. Wystarczy `computation.compute("1q234")` .

---

```
    @Test
    void notAlphanumeric(){
        assertThrows(NumberFormatException.class,
                () -> computation.compute(String.valueOf(Integer.parseInt("!@#$"))),
                "Not alphanumeric");
    }
```
to też zawsze przechodzi. Niepotrzebnie starasz się zrobić konwersję string->int->string.  
Ta sama sytuacja jest w teście `emptyString`.

## W LuhnChecksumComputing

zdecydowałeś się na takie "czyszczenie" argumentu z wejścia:
`this.number = input.trim().replace(" ", "");`
O ile do trim nie mam zarzutu, to `replace(" ", "")` może być zbyt słabe:
- usuwasz tylko PIERWSZĄ spację, więc `" 12 34"` zamieni w `"12 34"` lub `"1 2 3 4"` w `"12 3 4"`
- nie usuwasz innych białych znaków (np. tabulatora), np: `"12  34"` pozostanie `"12  34"`
Powinieneś użyć `replaceAll("\\s+", "")` - usunie to wszystkie białe znaki. A w takim razie `trim` na poczatku nie jest potrzebny:
`this.number = input.trim().replaceAll("\\s+", "");`  

`"\\s+"` to wyrażenie regularne,  `\\s` oznacza jakikolwiek biały znak, a `+` występujący przynajmniej raz. Bez plusa by zadziałało tak samo, ale mniej wydajnie, bo jeśli masz wiele białych znaków, to `+` sprawia, że `replaceAll` usuwa je wszystkie na raz. A bez plusa usuwa każdy osobno.

## W Main oraz LuhnChecksumComputing
```
        try {
            if (Integer.parseInt(computation.compute(inputNumber)) <= 0) System.out.println("Input number should be grater than O");
            else {
                computation.compute(inputNumber);
                ChecksumPrinter.printChecksum(computation.compute(inputNumber));
            }
        } catch (NullPointerException e){
            System.out.println("Input error");
        } catch (NumberFormatException e) {
            System.out.println("Number contain non-digit chars or is < 0");
        } catch (IllegalArgumentException e){
            System.out.println("Please enter number");
        }
```
jest straszliwie pokombinowane. Aktualnie wykorzystujesz wyjątki z biblioteki standardowej do walidacji. Jest ich dużo i niepotrzbnie komplikują obsługę. Powinieneś dodać własny wyjątek `InputValidationException`, który będzie przenosił informacje o tym co poszło nie tak. Wówczas ten kod uprości się do czegoś takiego:

```
        try {
            var result = computation.compute(inputNumber);
            ChecksumPrinter.printChecksum(result);
        } catch (InputValidationException e){
            System.out.println("Wrong input: " + e.getMessage());
        }
```

1. Dodaj `InputValidationException` rozszerzający `RuntimeException` z konstruktorem przyjmującym String:
```
public class InputValidationException extends RuntimeException {
    public InputValidationException(String msg) {
        super(msg);
    }
}
```
2. W `LuhnChecksumComputing` wyodrębnij kod weryfikujący `input` do osobnej metody `validate` i uruchamiaj ją jako pierwszą rzecz w metodzie `compute`.
3. `validate` nie powinien rzucać standardowych wyjątków, tylko nowo stworzony `InputValidationException`

**Comment by franc90** [comment]
Więcej o wyjątkach znajdziesz na oficjalnej stronie z dokumentacją javy: https://docs.oracle.com/javase/tutorial/essential/exceptions/index.html

**Comment by xmslyz** [comment]
zanim zacznę zmieniać muszę się spytać, czy w `tests` mogę w ten sposób sprawdzić wyjątki?

```
@Test
    void notANumber() {
        assertThrows(Main.InputValidationException.class, 
        () -> computation.compute("1r23e4"), 
        "Expected only digits");
    }
```
gdy w `public class LuhnChecksumComputing` zawarłem klasę:
```
private void validate(String input){
        if (!NumberUtils.isDigits(input)) throw new Main.InputValidationException("Expected only digits");
```

**Comment by franc90** [comment]
Tak to nawet byłoby preferowane nad używane BigIntigera.
Tylko jedna uwaga: `Main.InputValidationException` to mi sugeruje, że wyjątek jest zdefiniowany w `Main`. Powinien być w pakiecie `logic` inaczej znów będzie zależność `logic` na `main`.

**Comment by xmslyz** [comment]
Ach. Z ostatniego komentarza zrozumiałem, że 

```
public static class InputValidationException extends RuntimeException {
        public InputValidationException(String msg) {
            super(msg);
        }
    }
```
ma się znaleźć w `Main`. Dlateogo też m.in. o to pytałałem aby nie brnąć dalej w błąd. Najwyraźniej źle zrozumiałem. Przeniosę do `public class LuhnChecksumComputing`

Życzę dobrej niedzieli i do poniedziałku. Jutro niedziela ... a u ksiedza to dzień "roboczy" :]

**Comment by franc90** [comment]
Nawet nie do klasy `LuhnChecksumComputing`, a do samego pakietu `logic`. `InputValidationException` to jest część kontraktu wystawianego przez pakiet `logic`, warto żeby znalazł się w osobnym pliku jako publiczna klasa.

Dobrej niedzieli i szczęść Boże!

**Comment by xmslyz** [comment]
21. Września zacząłem się uczyć Javy od zera. 

Dziś mam już jakieś elementarne pojęcie. I dużo zawdzięczam tobie. Bóg zapłać.

**Comment by franc90** [comment]
Idziesz jak burza, jeszcze zrobimy z Ciebie programistę. :wink:
